### ISSUE TITLE
Non-free license

### ISSUE THREAD

**Issue by B-Eltzner** [seanh/storymaps#1]
I am not a native speaker; this post is not intended to be rude or insult anybody.

(Almost) all files in the /src/org/json folder are under the "json license" including the morality clause "The Software shall be used for Good, not Evil."
This license is regarded non-free by GNU/FSF, Debian, Fedora, Red Hat and Google and is not approved by OSI.
If you would like your program to be distributable as free and open source software, it might be best to remove or substitute these files. Alternative implementations for java are suggested e.g. at http://wiki.debian.org/qa.debian.org/jsonevil.

**Comment by seanh** [comment]
Hi, yes you're right, the json implementation should be replaced with another which shouldn't be too hard as I don't think it's even used for much. I've known about this issue for a while (and it's currently stopping storymaps from getting into debian) but I haven't had time to do the work

**Comment by mquinson** [comment]
Hello, storymaps is currently included in Debian, with a patch changing the json library. It uses the google version of the JSON library, which solves the licensing issues.

Here is the corresponding patch:  http://sources.debian.net/src/storymaps/1.0%2Bdfsg-2/debian/patches/use_google_gson/

Thanks for this nice program

**Comment by seanh** [comment]
Thanks! It's wonderful to see this in Debian. I've applied the patch to my master branch on GitHub
