### ISSUE TITLE
Please integrate the other Debian patches

### ISSUE THREAD

**Issue by mquinson** [seanh/storymaps#4]
Hello,

I think that you may find the other Debian patches interesting too and may want to integrate them. You can find them here:
https://sources.debian.net/src/storymaps/1.0%2Bdfsg-3/debian/patches/

Thanks,

**Comment by seanh** [comment]
Done, I think most of them (`generate_pdfs_script`, `gpl_license`) were already applied, but I applied and pushed the `upstream_address_change` one. Thanks!
